name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack PassportX
      run: dotnet pack PassportX/PassportX.csproj -c Release --no-build --output ./packages
    - name: Pack PassportServiceX
      run: dotnet pack PassportServiceX/PassportServiceX.csproj -c Release --no-build --output ./packages
    - name: Push to NuGet
      run: dotnet nuget push "./packages/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
